### ISSUE TITLE
[Step1] Hello World

### ISSUE THREAD

**Issue by charlie-world** [0hwan-mog/study#2]
# [Step1] Hello World 구현 하기

`python3.7` 을 설치 후, `hello.py` 파일을 생성. 콘솔에 `Hello World` 가 출력되는 프로그램을 개발 하시오.

**Comment by 0hwan-mog** [comment]
이렇게 업로드 하면 되나용?
[HW1.zip](https://github.com/0hwan-mog/study/files/3413152/HW1.zip)
